# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  flowasset:
    image: flowasset
    build:
      context: .
      dockerfile: FlowAsset/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5210:5210
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
