# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  flowasset:
    image: flowasset
    build:
      context: .
      dockerfile: FlowAsset/Dockerfile
    ports:
      - 5210:5210
